type = "card"
title = "Awards"
description = "Honors and awards I have received."

[[items]]
title = "RMIT Research Stipend Scholarship (RRSS)"
subtitle = "RMIT University"
date = "2025"
content = "Full scholarship"

