[site]
title = "Jian Tang's HomePage"
description = "PhD student at the University of Example."
favicon = "/icon_rmit.svg"
last_updated = "April 3, 2026"

[author]
name = "Jian Tang"
title = "Ph.D. student"
institution = "RMIT University, Melbourne, Australia"
email = "kt4ngw@gmail.com"
avatar = "/bio2.jpg"

[social]
# Contact information (leave blank or delete to hide)

# email = "kt4ngw@gmail.com"
# location = "Melbourne, Australia"
# location_url = "https://maps.google.com"
# location_details = ["City campus, 124 La Trobe St, Melbourne VIC, Australia"]
google_scholar = "https://scholar.google.com/citations?user=9eH0NZgAAAAJ&hl=en"
github = "https://github.com/kt4ngw"
linkedin = "https://www.linkedin.com/in/kt4ngw/"

[features]
# Show a like button on the about page
enable_likes = true

# Display all subpages on a single page
enable_one_page_mode = false

[[navigation]]
title = "About"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "Publications"
type = "page"
target = "publications"
href = "/publications"


[[navigation]]
title = "Services"
type = "page"
target = "services"
href = "/services"

[[navigation]]
title = "Awards"
type = "page"
target = "awards"
href = "/awards"

[[navigation]]
title = "CV"
type = "cv"
target = "cv"
href = "/cv"
