
[[news]]
date = "2026-04"
content = "Honored to be invited to serve as a reviewer for <span class='text-accent font-medium'>IEEE TMC</span>. I like this journal very much and am excited to contribute to the community."

[[news]]
date = "2025-11"
content = "Thrilled to receive an offer of admission to the PhD program and the RMIT Research Stipend Scholarship from RMIT University. Many thanks to <span class='text-primary font-medium'>Dr. Xia</span> for the support."

[[news]]
date = "2025-09"
content = "Our paper about client sampling for federated learning has been accepted by <span class='text-accent font-medium'>IEEE TMC</span>."
[[news]]
date = "2025-06"
content = "Happy to have received my master’s degree from Chongqing University."

[[news]]
date = "2025-01"
content = "Our paper about client selection and bandwidth allocation for federated learning has been accepted by <span class='text-accent font-medium'>IEEE TMC</span>."

[[news]]
date = "2024-01"
content = "Our paper about client sampling for federated learning is accepted by <span class='text-accent font-medium'>IEEE ICC 2024</span>."
