[[news]]
date = "2026-07"
content = "Our paper, “Accelerating Federated Learning under Client Dropout via Joint Bandwidth Allocation and Prototype Fine-Tuning in Mobile Edge Computing Networks,” has been accepted for publication in <span class='text-accent font-medium'>IEEE Transactions on Mobile Computing (IEEE TMC)</span>."

[[news]]
date = "2026-07"
content = "I have received funding from the AWS RMAS Program."

[[news]]
date = "2026-04"
content = "I have been invited to serve as a reviewer for <span class='text-accent font-medium'>IEEE TMC</span>. I am honored and excited to contribute to the community."

[[news]]
date = "2025-11"
content = "I have received an offer of admission to the PhD program and the RMIT Research Stipend Scholarship from RMIT University. Many thanks to <span class='text-primary font-medium'>Dr. Xia</span> for the support."

[[news]]
date = "2025-09"
content = "Our paper, “Group-based Federated Learning with Cost-efficient Sampling Mechanism in Mobile Edge Computing Networks,” has been accepted for publication in <span class='text-accent font-medium'>IEEE Transactions on Mobile Computing (IEEE TMC)</span>."
[[news]]
date = "2025-06"
content = "I have received my master’s degree from Chongqing University."

[[news]]
date = "2025-01"
content = "Our paper, “Joint Class-Balanced Client Selection and Bandwidth Allocation for Cost-Efficient Federated Learning in Mobile Edge Computing Networks,” has been accepted for publication in <span class='text-accent font-medium'>IEEE Transactions on Mobile Computing (IEEE TMC)</span>."

[[news]]
date = "2024-01"
content = "Our paper, “Energy-Efficient Client Sampling for Federated Learning in Heterogeneous Mobile Edge Computing Networks,” has been accepted for presentation at <span class='text-accent font-medium'>IEEE ICC 2024</span>."
