
[[news]]
date = "2026-04"
content = "I have been invited to serve as a reviewer for IEEE TMC. I would like to thank the Associate Editor. I greatly admire this journal."

[[news]]
date = "2025-11"
content = "I have received an offer of admission to the PhD program and RMIT Research Stipend Scholarship from RMIT University. Many thanks to Dr. Xia."

[[news]]
date = "2025-09"
content = "Our paper about client sampling for federated learning has been accepted by IEEE TMC."

[[news]]
date = "2025-06"
content = "I received my master’s degree from Chongqing University."

[[news]]
date = "2025-01"
content = "Our paper about client selection and bandwidth allocation for federated learning has been accepted by IEEE TMC."

[[news]]
date = "2024-01"
content = "Our paper about client sampling for federated learning is accepted by IEEE ICC 2024."
